#=======================================================
#Plugin Page: https://www.spigotmc.org/resources/39103
#Support: https://bghddevelopment.com/discord
#=======================================================
#Commands:
#/build - buildmode.toggle
#/build (playername) - buildmode.others
#buildmode.notify - Notify players of being enabled/disabled.
#=======================================================
#Messages:
InvalidUsage: "&cIncorrect usage! Use this command like this: /build <player>"
OfflinePlayer: "&cYou can not toggle BuildMode for a offline player!"
Enabled: "&7You have &aEnabled &7BuildMode!"
Disabled: "&7You have &cDisabled &7BuildMode!"
EnabledOther: "&7You have &aEnabled &7BuildMode for &e%player%"
DisabledOther: "&7You have &cDisabled &7BuildMode for &e%player%"
EnabledNotification: "&7&o[%player%: &e&oEnabled BuildMode&7&o]"
DisabledNotification: "&7&o[%player%: &e&oDisabled BuildMode&7&o]"
# Worlds List | To blacklist/whitelist all worlds put []
WorldsList:
  - 'world1'
  - 'world2'
  - 'world3'
# Should worlds on WorldsList be blacklisted or whitelisted?
# true = worlds list will be blacklisted | false = worlds list will be whitelisted.
# Blacklisted Worlds: can't build in worlds if on the list.
# Whitelisted Worlds: can build in worlds if on the list.
blacklistedWorlds: false