name: BuildModeBGHD
version: ${project.version}
main: me.noodles.buildmode.main.MainBuildMode
authors: [BGHDDevelopment]
website: https://bghddevelopment.com/
commands:
  build:
    description: Toggle BuildMode